### ISSUE TITLE
Support custom wildcard specifications

### ISSUE THREAD

**Issue by mattklein123** [rbresalier/sync_project_with_scm#1]
Thanks for maintaining this. In old versions of the macro it was possible to do something like this:
```
<my_sources>=*.py;*.sh;*.json;*.sls;*.cmake;*.proto;*.go;*.yaml;*.md;Makefile;*BUILD;WORKSPACE;*.bzl;<sources>

dir=+/foo, <my_sources>
```

That doesn't appear to be supported anymore. I hacked my custom list into the macro itself but it would be cool if this was still supported.

**Comment by rbresalier** [comment]
I just pushed this functionality onto github with latest commit. It was missing because there are 2 different threads on the SlickEdit forum about this macro and the wildcard group functionality was in a thread that I did not see when I forked off my version. The functionality is there now.

**Comment by mattklein123** [comment]
Thank you!!!
